<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstablishmentSeeder extends Seeder
{
    public function run(): void
    {
        // Temporarily disable FK checks to allow truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate table to reset (optional: comment out if appending)
        DB::table('establishments')->truncate();

        $establishments = [
            [
                'e_id' => 1,
                'e_name' => 'Sri Lanka Army',
                'abb_name' => 'SL ARMY',
                'type_code' => 1,
                'serial_number' => null,
            ],
            [
                'e_id' => 2,
                'e_name' => "Commander's Secretariat",
                'abb_name' => "Comd's Sec",
                'type_code' => 32,
                'serial_number' => null,
            ],
            [
                'e_id' => 3,
                'e_name' => 'Chief of Staff Office',
                'abb_name' => 'COS Office',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 4,
                'e_name' => 'Deputy Chief of Staff Office',
                'abb_name' => 'DCOS Office',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 5,
                'e_name' => 'Headquarters Sri Lanka Army Volunteer Force',
                'abb_name' => 'HQ SLAVF',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 6,
                'e_name' => "Military Secretary's Branch",
                'abb_name' => 'MS Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 7,
                'e_name' => 'General Staff Branch',
                'abb_name' => 'GS Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 8,
                'e_name' => 'Financial Management Branch',
                'abb_name' => 'Fin Mgmt Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 9,
                'e_name' => "Adjutant General's Branch",
                'abb_name' => 'AG Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 10,
                'e_name' => "Quarter Master General's Branch",
                'abb_name' => 'QMG Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 11,
                'e_name' => 'Master General Ordnance Branch',
                'abb_name' => 'MGO Br',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 12,
                'e_name' => 'Office of Director General Infantry',
                'abb_name' => 'Office of DG Inf',
                'type_code' => 3,
                'serial_number' => null,
            ],
            [
                'e_id' => 13,
                'e_name' => 'Office of Chief Filed Engineer',
                'abb_name' => 'Office of CFE',
                'type_code' => 32,
                'serial_number' => null,
            ],
            [
                'e_id' => 14,
                'e_name' => 'Office of Chief Signal Officer',
                'abb_name' => 'Office of CSO',
                'type_code' => 32,
                'serial_number' => null,
            ],
            [
                'e_id' => 15,
                'e_name' => 'Office of Director General Army Health Services',
                'abb_name' => 'Office of DGAHS',
                'type_code' => 32,
                'serial_number' => null,
            ],
            [
                'e_id' => 16,
                'e_name' => 'Judge Advocate General Office',
                'abb_name' => 'JAG Office',
                'type_code' => 32,
                'serial_number' => null,
            ],
            [
                'e_id' => 17,
                'e_name' => 'Directorate of Operations',
                'abb_name' => 'Dte of Ops',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 18,
                'e_name' => 'Directorate of Overseas Operations ',
                'abb_name' => 'Dte of OO',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 19,
                'e_name' => 'Directorate of Training',
                'abb_name' => 'Dte of Trg',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 20,
                'e_name' => 'Directorate of Plans',
                'abb_name' => 'Dte of Plans',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 21,
                'e_name' => 'Directorate of Military Intelligence',
                'abb_name' => 'Dte of MI',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 22,
                'e_name' => 'Directorate of Psychological Operations',
                'abb_name' => 'Dte of Psy Ops',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 23,
                'e_name' => 'Directorate of Staff Duties',
                'abb_name' => 'Dte of SD',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 24,
                'e_name' => 'Directorate of Media & Psychological Operations',
                'abb_name' => 'Dte of Media & Psy Ops',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 25,
                'e_name' => 'Directorate of Sports',
                'abb_name' => 'Dte of Sports',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 26,
                'e_name' => 'Directorate of Information Technology',
                'abb_name' => 'Dte of IT',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 27,
                'e_name' => 'Directorate of Infantry',
                'abb_name' => 'Dte of Inf',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 28,
                'e_name' => 'Directorate of Budget and Financial Management',
                'abb_name' => 'Dte of B & FM',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 29,
                'e_name' => 'Directorate of Internal Audit',
                'abb_name' => 'Dte of IA',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 30,
                'e_name' => 'Directorate of Pay and Records',
                'abb_name' => 'Dte of P & R',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 31,
                'e_name' => 'Directorate of Assets Management',
                'abb_name' => 'Dte of AM',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 32,
                'e_name' => 'Directorate of Agriculture and Livestock',
                'abb_name' => 'Dte of A & L',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 33,
                'e_name' => 'Directorate of Army Benevolent Fund ',
                'abb_name' => 'Dte of ABF',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 34,
                'e_name' => 'Directorate of Finance',
                'abb_name' => 'Dte of Fin',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 35,
                'e_name' => 'Directorate of Personnel Administration',
                'abb_name' => 'Dte of PA',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 36,
                'e_name' => 'Directorate of Army Band and Perfoming Arts ',
                'abb_name' => 'Dte of AB & PA',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 38,
                'e_name' => 'Directorate of Provost ',
                'abb_name' => 'Dte of Pro',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 39,
                'e_name' => 'Directorate of Welfare',
                'abb_name' => 'Dte of Welfare',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 40,
                'e_name' => 'Directorate of Veterans Affairs and Rehabilitation',
                'abb_name' => 'Dte of VA & Rehab',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 41,
                'e_name' => 'Directorate of Rehabilitation',
                'abb_name' => 'Dte of Rehab',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 42,
                'e_name' => 'Directorate of Human Rights and Humanitarian Law',
                'abb_name' => 'Dte of HR & HL',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 43,
                'e_name' => 'Directorate of Recruiting',
                'abb_name' => 'Dte of Rec',
                'type_code' => 4,
                'serial_number' => null,
            ],
            [
                'e_id' => 1052,
                'e_name' => '17 Battalion National Cadet Corps',
                'abb_name' => '17 NCC',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1053,
                'e_name' => 'Golfhill Resort',
                'abb_name' => 'Golfhill Resort',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1054,
                'e_name' => '2 Signal Brigade',
                'abb_name' => '2 Sig Bde',
                'type_code' => 8,
                'serial_number' => null,
            ],
            [
                'e_id' => 1055,
                'e_name' => '2 Signal Brigade Staff',
                'abb_name' => '2 Sig Bde Staff',
                'type_code' => 28,
                'serial_number' => null,
            ],
            [
                'e_id' => 1056,
                'e_name' => 'Regional Ordnance Depot Complex – Mullaitivu',
                'abb_name' => 'RODC - MLT',
                'type_code' => 16,
                'serial_number' => null,
            ],
            [
                'e_id' => 1061,
                'e_name' => 'OC TROOPS - SLCMP',
                'abb_name' => 'OC TROOPS - SECMP',
                'type_code' => 16,
                'serial_number' => null,
            ],
            [
                'e_id' => 1062,
                'e_name' => 'District General Hospital Nawalapitiya',
                'abb_name' => 'Distr Gen Hosp Nawalapitiya',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1063,
                'e_name' => 'University of Jayawardenepura',
                'abb_name' => 'University of Jayawardenepura',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1064,
                'e_name' => 'Nurses Training School - Kadana',
                'abb_name' => 'Nurses Training School - Kadana',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1066,
                'e_name' => 'National Institute of Health - Kadugannawa',
                'abb_name' => 'National Institute of Health - Kadugannawa',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1067,
                'e_name' => 'MRI School - Borella',
                'abb_name' => 'MRI School - Borella',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1068,
                'e_name' => 'President House Katharagama',
                'abb_name' => 'President House Katharagama',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1069,
                'e_name' => 'Sri Lanka Army Infantry Battalion training school - Kaluabathenna',
                'abb_name' => 'SLAIBTS - Kaluabathenna',
                'type_code' => 20,
                'serial_number' => null,
            ],
            [
                'e_id' => 1070,
                'e_name' => 'Hawa Eliya Holiday Resort - Nuwara Eliya',
                'abb_name' => 'Hawa Eliya Holiday Resort - Nuwara Eliya',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1072,
                'e_name' => 'Provost Coy - Thirumurikandi',
                'abb_name' => 'Provost Coy - Thirumurikandi',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1074,
                'e_name' => 'Army Commander Bungalow - Ampara',
                'abb_name' => 'Army Commander Bungalow - Ampara',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1075,
                'e_name' => '18 Battalion National Cadet Corps',
                'abb_name' => '18 NCC',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1076,
                'e_name' => 'District General Hospital- Embilipitiya',
                'abb_name' => 'District General Hospital- Embilipitiya',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1077,
                'e_name' => 'Base Hospital Marawila',
                'abb_name' => 'Base Hospital Marawila',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1078,
                'e_name' => 'National Sports Council',
                'abb_name' => 'National Sports Council',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1079,
                'e_name' => 'Sri lanka Air Force Hospital - Katunayaka',
                'abb_name' => 'SLAF Hosp - Katunayaka',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1080,
                'e_name' => 'Civil Security Department HQ Gomarankadawala',
                'abb_name' => 'CSD HQ Gomarankadawala',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1081,
                'e_name' => 'Maitland Place Multi Facility Complex',
                'abb_name' => 'Maitland Place Multi Facility Complex',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1082,
                'e_name' => '34 National Cadet Corps',
                'abb_name' => '34 NCC',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1086,
                'e_name' => '142 Rocket Battery',
                'abb_name' => '142 Rocket Bty',
                'type_code' => 23,
                'serial_number' => null,
            ],
            [
                'e_id' => 1087,
                'e_name' => 'District General Hospital - Trincomalee',
                'abb_name' => 'District General Hospital - Trincomalee',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1088,
                'e_name' => 'District General Hospital - Kegalle',
                'abb_name' => 'District General Hospital - Kegalle',
                'type_code' => 21,
                'serial_number' => null,
            ],
            [
                'e_id' => 1089,
                'e_name' => 'Base Hospital - Thabuththegama',
                'abb_name' => 'Base Hospital - Thabuththegama',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1090,
                'e_name' => 'Uva Wellassa University Of Sri Lanka',
                'abb_name' => 'Uva Wellassa University Of Sri Lanka',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1091,
                'e_name' => 'Security Force Headquarters (West) - SFHQ (West)',
                'abb_name' => 'Security Force Headquarters (West) - SFHQ (West)',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1092,
                'e_name' => 'Headquarters 12 Infantry Division - HQ 12 Inf Div',
                'abb_name' => 'Headquarters 12 Infantry Division - HQ 12 Inf Div',
                'type_code' => 30,
                'serial_number' => null,
            ],
            [
                'e_id' => 1093,
                'e_name' => '121 Infantry Brigade - HQ 121 Inf Bde',
                'abb_name' => '121 Infantry Brigade - HQ 121 Inf Bde',
                'type_code' => 30,
                'serial_number' => null,
            ],
            // TODO: Add the full remaining rows (44-1051, 1057-1060, etc.) from your complete SQL dump here.
            // If you paste the full SQL, I can regenerate the complete array.
        ];

        DB::table('establishments')->insert($establishments);

        // Re-enable FK checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}